CRM/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('',views.CasesList.as_view(), name='home'),
    #path('', views.CasesList.as_view(), name='home'),
]

EircCRM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CRM.urls')),
]

CRM/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Tasks_status(models.Model):
    task_status_id = models.AutoField(primary_key=True)
    task_status = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.task_status


class Tasks(models.Model):
    task_id = models.AutoField(primary_key=True)
    task_name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.task_name


class Cases(models.Model):
    case_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, unique=True)
    task_id = models.ForeignKey(Tasks, on_delete=models.CASCADE, null=True)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    task_status = models.ForeignKey(Tasks_status, to_field='task_status_id', on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['-created_on']

        def __str__(self):
            return Tasks.task_name

CRM/views.py
from django.shortcuts import render
from django.views import generic
from .models import Cases
# Create your views here.

class CasesList(generic.ListView):
    queryset = Cases.objects.order_by('-created_on')
    template_name = 'index.html'

templates/base.html
<!DOCTYPE html>
<html>
{% load static %}

    <head>
        <title>Django Central</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-image: url({% static 'media/background2.png' %});
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">EIRC CRM</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                           <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Контакты</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->

        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Copyright &copy; bpka</p>
        </footer>
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #efefef;
    }
</style>

<header class="masthead">

</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for case in cases_list %}
            <div class="card mb-4">
                <div class="card-body">
                    {% if case.task_status_id < 10 %}
                        <h4 class="card-title">{{ case.title }}</h4>
                        <p class="card-text text-muted h6">{{ case.created_on}} | {{ case.task_status}} </p>
                        <p class="card-text">{{case.content|slice:":200" }}</p>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{%endblock%}